services:
  portfolio_app:    
    container_name: portfolio_net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build: 
      context: .
      dockerfile: ./Dockerfile  
    # expose:
    #   - "8080"
    #   - "8081"
    ports:
      - 8080:8080
      - 8081:8081
    volumes:     
      - /srv/docker/volumes/portfolio/Data:/app/Data 
      - /srv/docker/volumes/porffolio/resume:/app/wwwroot/resume
    restart: unless-stopped
    networks:
      - webapp

#   nginx:
#     container_name: nginx_server
#     image: nginx:1.27.0-alpine3.19-slim
#     environment:
#     # - NGINX_HOST=foobar.com
#         - NGINX_PORT=80
#     ports:
#         - 80:80
#         - 443:443
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d
#     restart: always
#     networks: 
#         - webapp
    
networks:
    webapp:
        driver: bridge
        external: true       