
name: Deployment to VPS of my portfolio built with Blazor .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4      
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  deploy:
    needs: [build]
    runs-on: self-hosted

    name: Deploy to VPS
    steps:
      - name: Checkout our main branch
        uses: actions/checkout@v4
                  
      - name: Run docker
        run: docker compose up --build --force-recreate -d
      
      # -f option to clear cache without any promts
      - name: Clear all docker cache to keep VPS disk clean
        run: docker builder prune -f
            
       #- name: Clear all unused resources by docker
       #  run: docker system prune -a -f